# Generated by Django 5.0.6 on 2024-07-01 00:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('posturl', models.SlugField(blank=True, max_length=200, unique=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('post_image_alt', models.CharField(blank=True, max_length=200)),
                ('published_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('snippet', models.CharField(blank=True, max_length=255)),
                ('last_updated_datetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
