# Generated by Django 5.0.6 on 2024-07-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iamablogger', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(related_name='blog_posts', to='Iamablogger.category'),
        ),
    ]
