# Generated by Django 5.0.6 on 2024-07-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iamablogger', '0004_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post_image_alt',
        ),
    ]
