# Generated by Django 5.0.6 on 2024-07-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iamablogger', '0005_remove_blogpost_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_image_alt',
            field=models.CharField(default='Image', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_image_name',
            field=models.CharField(default='Image', max_length=200),
        ),
    ]
