# Generated by Django 5.0.6 on 2024-06-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_customuser_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password1',
        ),
    ]
